/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as CapsulesIndexRouteImport } from './routes/capsules.index'
import { Route as CapsulesIdRouteImport } from './routes/capsules.$id'
import { Route as CapsulesNewRouteImport } from './routes/capsules.new'
import { Route as SharedTokenRouteImport } from './routes/shared.$token'
import { Route as CapsulesIdIndexRouteImport } from './routes/capsules.$id.index'
import { Route as CapsulesIdChatRouteImport } from './routes/capsules.$id.chat'
import { Route as CapsulesIdFamilyRouteImport } from './routes/capsules.$id.family'
import { Route as CapsulesIdLegacyRouteImport } from './routes/capsules.$id.legacy'
import { Route as CapsulesIdMemoriesRouteImport } from './routes/capsules.$id.memories'
import { Route as CapsulesIdTimeVaultRouteImport } from './routes/capsules.$id.time-vault'
import { Route as CapsulesIdTimelineRouteImport } from './routes/capsules.$id.timeline'
import { Route as CapsulesIdUploadRouteImport } from './routes/capsules.$id.upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const CapsulesIndexRoute = CapsulesIndexRouteImport.update({
  id: '/capsules/',
  path: '/capsules/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapsulesIdRoute = CapsulesIdRouteImport.update({
  id: '/capsules/$id',
  path: '/capsules/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CapsulesNewRoute = CapsulesNewRouteImport.update({
  id: '/capsules/new',
  path: '/capsules/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CapsulesIdIndexRoute = CapsulesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CapsulesIdRoute,
} as any)
const CapsulesIdChatRoute = CapsulesIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => CapsulesIdRoute,
} as any)
const CapsulesIdFamilyRoute = CapsulesIdFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => CapsulesIdRoute,
} as any)
const CapsulesIdLegacyRoute = CapsulesIdLegacyRouteImport.update({
  id: '/legacy',
  path: '/legacy',
  getParentRoute: () => CapsulesIdRoute,
} as any)
const CapsulesIdMemoriesRoute = CapsulesIdMemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => CapsulesIdRoute,
} as any)
const CapsulesIdTimeVaultRoute = CapsulesIdTimeVaultRouteImport.update({
  id: '/time-vault',
  path: '/time-vault',
  getParentRoute: () => CapsulesIdRoute,
} as any)
const CapsulesIdTimelineRoute = CapsulesIdTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => CapsulesIdRoute,
} as any)
const CapsulesIdUploadRoute = CapsulesIdUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => CapsulesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/capsules/$id': typeof CapsulesIdRouteWithChildren
  '/capsules/new': typeof CapsulesNewRoute
  '/shared/$token': typeof SharedTokenRoute
  '/capsules/': typeof CapsulesIndexRoute
  '/capsules/$id/chat': typeof CapsulesIdChatRoute
  '/capsules/$id/family': typeof CapsulesIdFamilyRoute
  '/capsules/$id/legacy': typeof CapsulesIdLegacyRoute
  '/capsules/$id/memories': typeof CapsulesIdMemoriesRoute
  '/capsules/$id/time-vault': typeof CapsulesIdTimeVaultRoute
  '/capsules/$id/timeline': typeof CapsulesIdTimelineRoute
  '/capsules/$id/upload': typeof CapsulesIdUploadRoute
  '/capsules/$id/': typeof CapsulesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/capsules/new': typeof CapsulesNewRoute
  '/shared/$token': typeof SharedTokenRoute
  '/capsules': typeof CapsulesIndexRoute
  '/capsules/$id/chat': typeof CapsulesIdChatRoute
  '/capsules/$id/family': typeof CapsulesIdFamilyRoute
  '/capsules/$id/legacy': typeof CapsulesIdLegacyRoute
  '/capsules/$id/memories': typeof CapsulesIdMemoriesRoute
  '/capsules/$id/time-vault': typeof CapsulesIdTimeVaultRoute
  '/capsules/$id/timeline': typeof CapsulesIdTimelineRoute
  '/capsules/$id/upload': typeof CapsulesIdUploadRoute
  '/capsules/$id': typeof CapsulesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/capsules/$id': typeof CapsulesIdRouteWithChildren
  '/capsules/new': typeof CapsulesNewRoute
  '/shared/$token': typeof SharedTokenRoute
  '/capsules/': typeof CapsulesIndexRoute
  '/capsules/$id/chat': typeof CapsulesIdChatRoute
  '/capsules/$id/family': typeof CapsulesIdFamilyRoute
  '/capsules/$id/legacy': typeof CapsulesIdLegacyRoute
  '/capsules/$id/memories': typeof CapsulesIdMemoriesRoute
  '/capsules/$id/time-vault': typeof CapsulesIdTimeVaultRoute
  '/capsules/$id/timeline': typeof CapsulesIdTimelineRoute
  '/capsules/$id/upload': typeof CapsulesIdUploadRoute
  '/capsules/$id/': typeof CapsulesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/search'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/capsules/$id'
    | '/capsules/new'
    | '/shared/$token'
    | '/capsules/'
    | '/capsules/$id/chat'
    | '/capsules/$id/family'
    | '/capsules/$id/legacy'
    | '/capsules/$id/memories'
    | '/capsules/$id/time-vault'
    | '/capsules/$id/timeline'
    | '/capsules/$id/upload'
    | '/capsules/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/search'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/capsules/new'
    | '/shared/$token'
    | '/capsules'
    | '/capsules/$id/chat'
    | '/capsules/$id/family'
    | '/capsules/$id/legacy'
    | '/capsules/$id/memories'
    | '/capsules/$id/time-vault'
    | '/capsules/$id/timeline'
    | '/capsules/$id/upload'
    | '/capsules/$id'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/search'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/capsules/$id'
    | '/capsules/new'
    | '/shared/$token'
    | '/capsules/'
    | '/capsules/$id/chat'
    | '/capsules/$id/family'
    | '/capsules/$id/legacy'
    | '/capsules/$id/memories'
    | '/capsules/$id/time-vault'
    | '/capsules/$id/timeline'
    | '/capsules/$id/upload'
    | '/capsules/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  DashboardRoute: typeof DashboardRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  CapsulesIdRoute: typeof CapsulesIdRouteWithChildren
  CapsulesNewRoute: typeof CapsulesNewRoute
  SharedTokenRoute: typeof SharedTokenRoute
  CapsulesIndexRoute: typeof CapsulesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capsules/': {
      id: '/capsules/'
      path: '/capsules'
      fullPath: '/capsules/'
      preLoaderRoute: typeof CapsulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capsules/$id': {
      id: '/capsules/$id'
      path: '/capsules/$id'
      fullPath: '/capsules/$id'
      preLoaderRoute: typeof CapsulesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capsules/new': {
      id: '/capsules/new'
      path: '/capsules/new'
      fullPath: '/capsules/new'
      preLoaderRoute: typeof CapsulesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capsules/$id/': {
      id: '/capsules/$id/'
      path: '/'
      fullPath: '/capsules/$id/'
      preLoaderRoute: typeof CapsulesIdIndexRouteImport
      parentRoute: typeof CapsulesIdRoute
    }
    '/capsules/$id/chat': {
      id: '/capsules/$id/chat'
      path: '/chat'
      fullPath: '/capsules/$id/chat'
      preLoaderRoute: typeof CapsulesIdChatRouteImport
      parentRoute: typeof CapsulesIdRoute
    }
    '/capsules/$id/family': {
      id: '/capsules/$id/family'
      path: '/family'
      fullPath: '/capsules/$id/family'
      preLoaderRoute: typeof CapsulesIdFamilyRouteImport
      parentRoute: typeof CapsulesIdRoute
    }
    '/capsules/$id/legacy': {
      id: '/capsules/$id/legacy'
      path: '/legacy'
      fullPath: '/capsules/$id/legacy'
      preLoaderRoute: typeof CapsulesIdLegacyRouteImport
      parentRoute: typeof CapsulesIdRoute
    }
    '/capsules/$id/memories': {
      id: '/capsules/$id/memories'
      path: '/memories'
      fullPath: '/capsules/$id/memories'
      preLoaderRoute: typeof CapsulesIdMemoriesRouteImport
      parentRoute: typeof CapsulesIdRoute
    }
    '/capsules/$id/time-vault': {
      id: '/capsules/$id/time-vault'
      path: '/time-vault'
      fullPath: '/capsules/$id/time-vault'
      preLoaderRoute: typeof CapsulesIdTimeVaultRouteImport
      parentRoute: typeof CapsulesIdRoute
    }
    '/capsules/$id/timeline': {
      id: '/capsules/$id/timeline'
      path: '/timeline'
      fullPath: '/capsules/$id/timeline'
      preLoaderRoute: typeof CapsulesIdTimelineRouteImport
      parentRoute: typeof CapsulesIdRoute
    }
    '/capsules/$id/upload': {
      id: '/capsules/$id/upload'
      path: '/upload'
      fullPath: '/capsules/$id/upload'
      preLoaderRoute: typeof CapsulesIdUploadRouteImport
      parentRoute: typeof CapsulesIdRoute
    }
  }
}

interface CapsulesIdRouteChildren {
  CapsulesIdChatRoute: typeof CapsulesIdChatRoute
  CapsulesIdFamilyRoute: typeof CapsulesIdFamilyRoute
  CapsulesIdLegacyRoute: typeof CapsulesIdLegacyRoute
  CapsulesIdMemoriesRoute: typeof CapsulesIdMemoriesRoute
  CapsulesIdTimeVaultRoute: typeof CapsulesIdTimeVaultRoute
  CapsulesIdTimelineRoute: typeof CapsulesIdTimelineRoute
  CapsulesIdUploadRoute: typeof CapsulesIdUploadRoute
  CapsulesIdIndexRoute: typeof CapsulesIdIndexRoute
}

const CapsulesIdRouteChildren: CapsulesIdRouteChildren = {
  CapsulesIdChatRoute: CapsulesIdChatRoute,
  CapsulesIdFamilyRoute: CapsulesIdFamilyRoute,
  CapsulesIdLegacyRoute: CapsulesIdLegacyRoute,
  CapsulesIdMemoriesRoute: CapsulesIdMemoriesRoute,
  CapsulesIdTimeVaultRoute: CapsulesIdTimeVaultRoute,
  CapsulesIdTimelineRoute: CapsulesIdTimelineRoute,
  CapsulesIdUploadRoute: CapsulesIdUploadRoute,
  CapsulesIdIndexRoute: CapsulesIdIndexRoute,
}

const CapsulesIdRouteWithChildren = CapsulesIdRoute._addFileChildren(
  CapsulesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  DashboardRoute: DashboardRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  CapsulesIdRoute: CapsulesIdRouteWithChildren,
  CapsulesNewRoute: CapsulesNewRoute,
  SharedTokenRoute: SharedTokenRoute,
  CapsulesIndexRoute: CapsulesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
